name: release
on:
  workflow_dispatch:
  release:
    types:
    - published

env:
  NuGetDirectory: ${{ github.workspace }}/nuget

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
    - name: Create Package
      run: dotnet pack --configuration Release --output ${{ env.NuGetDirectory }}
    - name: Publish Package
      run: dotnet nuget push ${{ env.NuGetDirectory }}/*.nupkg --source https://nuget.pkg.github.com/vws4ls/index.json --api-key ${{ secrets.NUGET_AUTH_TOKEN }}    
